spring:
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: 6379
      connect-timeout: 30s
      timeout: 30s
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
        shutdown-timeout: 100ms
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/wallet_service?currentSchema=wallet_service;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: password
  jpa:
    database: POSTGRESQL
    open-in-view: false
    hibernate:
      ddl-auto: update