services:
  db:
    build:
      dockerfile: Dockerfile-postgresql
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
    networks:
      - app-network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_started
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
    ports:
      - '8080:8080'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge